### ISSUE TITLE
Revisions arising from S-101 portrayal discussions

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/98-interoperability#11]
List of revisions to be proposed by S-101 Project Team portrayal subgroup to be obtained.

**Comment by DavidGrant-NIWC** [comment]
@rmalyankar:
* I assume this forum is for issue discussion, but does a document change necessarily involve a change proposal?
  * Is the plan to update the draft and submit all the incorporated changes as a package for approval?
* What is the way forward on viewing groups / viewing group layers? 
  * We will need to update the information in the various tables.
  * Mariners information other than 53000-53050 doesn't appear to be present and is not in the S-101 PC.
  * Most of the information which is present is duplicated in the registry and the S-101 PC.
    *  It may prove challenging to keep the document aligned.
    * There are already issues - for instance 26020 is used in the PC for "Restricted area, regulatory" (but may be removed in the next catalog).
    * Should registered items be removed from the document?

The answers to these questions will inform the path forward for https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/136; in particular we need to either add 53011-53024, or remove 53010.

**Comment by rmalyankar** [comment]
> * I assume this forum is for issue discussion, but does a document change necessarily involve a change proposal?
>   
>   * Is the plan to update the draft and submit all the incorporated changes as a package for approval?

There has to be _some_ kind of list of changes presented to the S-100 WG, be it as a table in a change proposal or in the usual comments form. If you can provide that list we can take it from there.

Since the document is already being edited and a redline already exists, providing the changes in the form of (another) redline would be undesirable.

> * What is the way forward on viewing groups / viewing group layers?
>   
>   * We will need to update the information in the various tables.
>   * Mariners information other than 53000-53050 doesn't appear to be present and is not in the S-101 PC.
>   * Most of the information which is present is duplicated in the registry and the S-101 PC.

Is the GI registry up-to-date and guaranteed to be kept up-to-date?
(If the S-101 PC does not contain mariner's information, and given that S-101 is not the only product on the system, the S-101 PC cannot be the authoritative source.)
The state, stability and completeness of content, and maintenance assurances for the relevant sections of the GI registry will inform decisions about the the path forward.

There is, I think a bigger problem here, if S-101 portrayal continues to be volatile close to the implementation date, and S-101 is treated as the de facto controlling specification for portrayal, it will be difficult for other products to be both ready and compatible on the implementation date.

**Comment by kusala9** [comment]
I don't think this is needed any more - S-98 Annex C receives issues from S-101PT as necessary and can be discussed here. Please reopen this if anything further is needed.
