### ISSUE TITLE
Interoperability identifiers for coverage datasets?

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/98-interoperability#54]
Should coverage products included in Phase 1 include _interoperabilityIdentifier_ attributes?

If yes:
1.  Should they be single (0..1 multiplicity) or multiple (0..* multiplicity)?
2.  Where should they be encoded (presumably in an HDF5 attribute or HDF5 dataset at the feature instance level, depending on whether the multiplicity is 0..1 or 0..*).

There are arguments for both "yes" and "no".

This decision needs to be made soon, by 27 June. Changing product specifications later (to either add or remove it) will be difficult and would delay approval.

**Comment by kusala9** [comment]
* This was raised at the S-101PT last week and the comment from IEC was that they didn't consider the ECDIS functionality required integration with interoperability identifier. 
* I'm guessing, as you say, this would be added as a hard wired attribute at the feature instance level but this would require a bespoke extension for each of the Phase 1 products, documented in S-98 Annex C, as they can't be added to the feature catalogue. 
* Or are you thinking add it to the feature catalogue? 
* Either way, we would need the Phase 1 coverage products to propose this to S-98 Annex C.

**Comment by rmalyankar** [comment]
Since there is a consensus that there is no current need to introduce interoperability identifiers in coverage products, I am closing this issue.
