### ISSUE TITLE
Requirements conflict regarding overscale pattern

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/98-interoperability#8]
The overscale pattern has a requirements conflict; S-101 PS 4.6 requires the pattern whenever `maximumDisplayScale` is exceeded but S-98 Annex C C-12.1.4 requires the pattern when twice the `maximumDisplayScale` is exceeded.

![image](https://github.com/iho-ohi/98-interoperability/assets/62906211/ed129d3d-bbaa-4b2e-89ac-f2738e8c386b)

**Comment by rmalyankar** [comment]
Needs confirmation. The language is from S-52 Ed. 6.1.1, extracted below. Is the cited language in S-101 intended to change this S-52 direction for S-100 ECDIS display purposes? What will the effect for dual-fuel systems be; if the user experience changes, is that OK?

> **3.2.3 (8b) Overscale area at scale boundary**
> All the chart data on the display must be shown at the same scale. In order to avoid leaving part of the display blank, the chart display may extend beyond the edge of a relatively large scale ENC to include information from an adjoining smaller scale ENC, which may be from a different "navigational purpose". The smaller scale data will normally be enlarged to match the larger scale ENC, and in this case the "overscale area" symbol should be used to identify any part of the chart display shown at two or more times the compilation scale. See Presentation Library, Part I, section 10.1.10.2 for details.
> 
> Note that this symbol applies only to the automatic overscaling performed by the ECDIS in matching ENCs at different compilation scales. It should not be applied to an overscale display deliberately requested by the mariner, which should trigger the overscale indication required by IMO Performance Standard section 6.1.1.

**Comment by DavidGrant-NIWC** [comment]
My understanding is that the S-52 requirement is with regard to compilation scale (double the compilation scale); the closest equivalent in S-100 would require referencing _optimumDisplayScale_ which is unused in S-101. S-101 _maximumDisplayScale_ is presumably already set to the maximum reasonable value beyond which the data would be considered "grossly" overscale.

In any case, either S-98 Annex C or the S-101 PS needs to be updated so the requirements don't contradict one another.

**Comment by rmalyankar** [comment]
S-52 apparently distinguishes between "overscale" and "grossly overscale". S-52 3.1.7 says "an overscale indication should be shown whenever the mariner selects a display scale that is larger than the compilation scale". The S-101 equivalent is the statement in S-101 relating to exceeding _maximumDisplayScale_. S-52 3.2.3 8(b) and Annex C 12.1.4 are addressing a different case.

I agree that one or both of S-101 and S-98 Annex C should be clarified. Perhaps as follows:- 

- Overscale by mariner action: Overscale pattern displayed when _maximumDisplayScale_ is exceeded.
- Automatic overscale to fill the chart window: Overscale pattern displayed when 2 X _maximumDisplayScale_ is exceeded.

This issue should be discussed, perhaps brought to the attention of ENCWG for input.

**Comment by DavidGrant-NIWC** [comment]
Note S-98 Annex C 12.1.4 para 3:
![image](https://github.com/iho-ohi/98-interoperability/assets/62906211/d55d86eb-807e-4550-9ece-e331b7a1096a)

**Comment by rmalyankar** [comment]
Yes, that would cover it for Annex C.

**Comment by rmalyankar** [comment]
To do for Annex C:

- Replace "symbol" -> "rule"
- Check whether the new IMO performance standards or IEC standards address this or whether the referral should be to the product specification(s).

**Comment by rmalyankar** [comment]
"symbol" replaced with "rule" in the NOTE:

New IMO Performance Standard:
> 6 SCALE
>>  6.1 ECDIS should provide an indication if:
>>>   .1 the information is displayed at a larger scale than that contained in the ENC;

so the only change for the second bullet is adding a citation of the IMO standard.

**Comment by DavidGrant-NIWC** [comment]
This issue only regards the overscale pattern requirement, specifically the removal of "X2" to harmonize with the S-101 PS. Other issues should be addressed separately.

**Comment by kusala9** [comment]
Update following S-101PT. optimumDisplayScale is included for testing in the v1.2 of the S-101PT. The alternative is to retain the x2 rule currently hardwired into S-52. Until S-101 conclude this discussion it's unlikely this will be resovled to the point where we can clarify the S-98 wording. Suggest this issue is paused until then.

**Comment by DavidGrant-NIWC** [comment]
Change proposal submitted.
